package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseClazz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Clazz extends BaseClazz<Clazz> {
	public static final Clazz dao = new Clazz();
}
