package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
	public static final Company dao = new Company();
}
