package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseJobTemplateDeploy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobTemplateDeploy extends BaseJobTemplateDeploy<JobTemplateDeploy> {
	public static final JobTemplateDeploy dao = new JobTemplateDeploy();


}
