package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseJobTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobTemplate extends BaseJobTemplate<JobTemplate> {
	public static final JobTemplate dao = new JobTemplate();
}
