package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Msg extends BaseMsg<Msg> {
	public static final Msg dao = new Msg();
}
