package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BasePlanClazzR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanClazzR extends BasePlanClazzR<PlanClazzR> {
	public static final PlanClazzR dao = new PlanClazzR();
}
