package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BasePlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plan extends BasePlan<Plan> {
	public static final Plan dao = new Plan();
}
