package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseResume;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resume extends BaseResume<Resume> {
	public static final Resume dao = new Resume();
}
