package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseResumeExper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResumeExper extends BaseResumeExper<ResumeExper> {
	public static final ResumeExper dao = new ResumeExper();
}
