package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseResumeExper;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResumeExper extends BaseResumeExper<ResumeExper> {
    public static final ResumeExper dao = new ResumeExper();

    public List<ResumeExper> findByResumeId(Integer resumeId) {
        return find("select * from t_resume_exper where resume_id = ? order by exper_id desc", resumeId);
    }
}
