package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseUserPlanR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPlanR extends BaseUserPlanR<UserPlanR> {
	public static final UserPlanR dao = new UserPlanR();
}
