package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseUserCompanyR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCompanyR extends BaseUserCompanyR<UserCompanyR> {
	public static final UserCompanyR dao = new UserCompanyR();
}
