package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseUserPlanR;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPlanR extends BaseUserPlanR<UserPlanR> {
    public static final UserPlanR dao = new UserPlanR();

    public List<UserPlanR> findPlanByUserId(String user_id, String apply_status) {
        return find("select r._id,r.`plan_already_hour`,r.`plan_already_score`,r.`apply_status`,p.*" +
                "from t_user_plan_r r left join t_plan p " +
                "on r.`plan_id` = p.`plan_id` " +
                "where r.`user_id`=? and r.apply_status = ? order by r.`_id` desc", user_id, apply_status);
    }
}
