package win.yulongsun.talents.model;

import win.yulongsun.talents.model.base.BaseUserPlanClazzR;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPlanClazzR extends BaseUserPlanClazzR<UserPlanClazzR> {
	public static final UserPlanClazzR dao = new UserPlanClazzR();
}
