package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanClazzR<M extends BasePlanClazzR<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("_id", Id);
	}

	public java.lang.Integer getId() {
		return get("_id");
	}

	public void setPlanId(java.lang.Integer planId) {
		set("plan_id", planId);
	}

	public java.lang.Integer getPlanId() {
		return get("plan_id");
	}

	public void setClazzId(java.lang.Integer clazzId) {
		set("clazz_id", clazzId);
	}

	public java.lang.Integer getClazzId() {
		return get("clazz_id");
	}

	public void setClazzDoneHour(java.lang.Integer clazzDoneHour) {
		set("clazz_done_hour", clazzDoneHour);
	}

	public java.lang.Integer getClazzDoneHour() {
		return get("clazz_done_hour");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
