package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResumeExper<M extends BaseResumeExper<M>> extends Model<M> implements IBean {

	public void setExperId(java.lang.Integer experId) {
		set("exper_id", experId);
	}

	public java.lang.Integer getExperId() {
		return get("exper_id");
	}

	public void setResumeId(java.lang.Integer resumeId) {
		set("resume_id", resumeId);
	}

	public java.lang.Integer getResumeId() {
		return get("resume_id");
	}

	public void setExperName(java.lang.String experName) {
		set("exper_name", experName);
	}

	public java.lang.String getExperName() {
		return get("exper_name");
	}

	public void setExperDesc(java.lang.String experDesc) {
		set("exper_desc", experDesc);
	}

	public java.lang.String getExperDesc() {
		return get("exper_desc");
	}

	public void setExperJobDesc(java.lang.String experJobDesc) {
		set("exper_job_desc", experJobDesc);
	}

	public java.lang.String getExperJobDesc() {
		return get("exper_job_desc");
	}

	public void setExperJob(java.lang.String experJob) {
		set("exper_job", experJob);
	}

	public java.lang.String getExperJob() {
		return get("exper_job");
	}

	public void setExperTime(java.lang.String experTime) {
		set("exper_time", experTime);
	}

	public java.lang.String getExperTime() {
		return get("exper_time");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
