package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlan<M extends BasePlan<M>> extends Model<M> implements IBean {

	public void setPlanId(java.lang.Integer planId) {
		set("plan_id", planId);
	}

	public java.lang.Integer getPlanId() {
		return get("plan_id");
	}

	public void setPlanName(java.lang.String planName) {
		set("plan_name", planName);
	}

	public java.lang.String getPlanName() {
		return get("plan_name");
	}

	public void setPlanDesc(java.lang.String planDesc) {
		set("plan_desc", planDesc);
	}

	public java.lang.String getPlanDesc() {
		return get("plan_desc");
	}

	public void setPlanImg(java.lang.String planImg) {
		set("plan_img", planImg);
	}

	public java.lang.String getPlanImg() {
		return get("plan_img");
	}

	public void setJobTemplateId(java.lang.Integer employTemplateId) {
		set("job_template_id", employTemplateId);
	}

	public java.lang.Integer getJobTemplateId() {
		return get("job_template_id");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}

	public java.lang.Integer getCreateBy() {
		return get("create_by");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
