package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanClazzR<M extends BasePlanClazzR<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("_id", Id);
	}

	public java.lang.Integer getId() {
		return get("_id");
	}

	public void setPlanId(java.lang.Integer planId) {
		set("plan_id", planId);
	}

	public java.lang.Integer getPlanId() {
		return get("plan_id");
	}

	public void setClassId(java.lang.Integer classId) {
		set("class_id", classId);
	}

	public java.lang.Integer getClassId() {
		return get("class_id");
	}

	public void setClassDoneHour(java.lang.Integer classDoneHour) {
		set("class_done_hour", classDoneHour);
	}

	public java.lang.Integer getClassDoneHour() {
		return get("class_done_hour");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
