package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClazz<M extends BaseClazz<M>> extends Model<M> implements IBean {

	public void setClazzId(java.lang.Integer clazzId) {
		set("clazz_id", clazzId);
	}

	public java.lang.Integer getClazzId() {
		return get("clazz_id");
	}

	public void setClazzPriority(java.lang.Integer clazzPriority) {
		set("clazz_priority", clazzPriority);
	}

	public java.lang.Integer getClazzPriority() {
		return get("clazz_priority");
	}

	public void setClazzName(java.lang.String clazzName) {
		set("clazz_name", clazzName);
	}

	public java.lang.String getClazzName() {
		return get("clazz_name");
	}

	public void setClazzImg(java.lang.String clazzImg) {
		set("clazz_img", clazzImg);
	}

	public java.lang.String getClazzImg() {
		return get("clazz_img");
	}

	public void setClazzBooks(java.lang.String clazzBooks) {
		set("clazz_books", clazzBooks);
	}

	public java.lang.String getClazzBooks() {
		return get("clazz_books");
	}

	public void setClazzHour(java.lang.Integer clazzHour) {
		set("clazz_hour", clazzHour);
	}

	public java.lang.Integer getClazzHour() {
		return get("clazz_hour");
	}

	public void setClazzScore(java.lang.Integer clazzScore) {
		set("clazz_score", clazzScore);
	}

	public java.lang.Integer getClazzScore() {
		return get("clazz_score");
	}

	public void setPlanId(java.lang.Integer planId) {
		set("plan_id", planId);
	}

	public java.lang.Integer getPlanId() {
		return get("plan_id");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
