package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobTemplateDeploy<M extends BaseJobTemplateDeploy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("_id", Id);
	}

	public java.lang.Integer getId() {
		return get("_id");
	}

	public void setTmpId(java.lang.Integer tmpId) {
		set("tmp_id", tmpId);
	}

	public java.lang.Integer getTmpId() {
		return get("tmp_id");
	}

	public void setStartAt(java.util.Date startAt) {
		set("start_at", startAt);
	}

	public java.util.Date getStartAt() {
		return get("start_at");
	}

	public void setEntAt(java.util.Date entAt) {
		set("ent_at", entAt);
	}

	public java.util.Date getEntAt() {
		return get("ent_at");
	}

	public void setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
	}

	public java.lang.Integer getIsActive() {
		return get("is_active");
	}

	public void setDeployAt(java.util.Date deployAt) {
		set("deploy_at", deployAt);
	}

	public java.util.Date getDeployAt() {
		return get("deploy_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
