package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResume<M extends BaseResume<M>> extends Model<M> implements IBean {

	public void setResumeId(java.lang.Integer resumeId) {
		set("resume_id", resumeId);
	}

	public java.lang.Integer getResumeId() {
		return get("resume_id");
	}

	public void setResumeName(java.lang.String resumeName) {
		set("resume_name", resumeName);
	}

	public java.lang.String getResumeName() {
		return get("resume_name");
	}

	public void setResumeDesc(java.lang.String resumeDesc) {
		set("resume_desc", resumeDesc);
	}

	public java.lang.String getResumeDesc() {
		return get("resume_desc");
	}

	public void setResumeGender(java.lang.String resumeGender) {
		set("resume_gender", resumeGender);
	}

	public java.lang.String getResumeGender() {
		return get("resume_gender");
	}

	public void setResumeAcademy(java.lang.String resumeAcademy) {
		set("resume_academy", resumeAcademy);
	}

	public java.lang.String getResumeAcademy() {
		return get("resume_academy");
	}

	public void setResumeIsStudy(java.lang.String resumeIsStudy) {
		set("resume_is_study", resumeIsStudy);
	}

	public java.lang.String getResumeIsStudy() {
		return get("resume_is_study");
	}

	public void setResumeMajor(java.lang.String resumeMajor) {
		set("resume_major", resumeMajor);
	}

	public java.lang.String getResumeMajor() {
		return get("resume_major");
	}

	public void setResumeGraduateAt(java.lang.String resumeGraduateAt) {
		set("resume_graduate_at", resumeGraduateAt);
	}

	public java.lang.String getResumeGraduateAt() {
		return get("resume_graduate_at");
	}

	public void setResumeMobile(java.lang.String resumeMobile) {
		set("resume_mobile", resumeMobile);
	}

	public java.lang.String getResumeMobile() {
		return get("resume_mobile");
	}

	public void setResumeEmail(java.lang.String resumeEmail) {
		set("resume_email", resumeEmail);
	}

	public java.lang.String getResumeEmail() {
		return get("resume_email");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}

	public java.lang.Integer getCreateBy() {
		return get("create_by");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
