package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClazz<M extends BaseClazz<M>> extends Model<M> implements IBean {

	public void setClazzId(java.lang.Integer clazzId) {
		set("clazz_id", clazzId);
	}

	public java.lang.Integer getClazzId() {
		return get("clazz_id");
	}

	public void setClazzName(java.lang.String clazzName) {
		set("clazz_name", clazzName);
	}

	public java.lang.String getClazzName() {
		return get("clazz_name");
	}

	public void setClazzDesc(java.lang.String clazzDesc) {
		set("clazz_desc", clazzDesc);
	}

	public java.lang.String getClazzDesc() {
		return get("clazz_desc");
	}

	public void setClazzImg(java.lang.String clazzImg) {
		set("clazz_img", clazzImg);
	}

	public java.lang.String getClazzImg() {
		return get("clazz_img");
	}

	public void setClazzRequire(java.lang.String clazzRequire) {
		set("clazz_require", clazzRequire);
	}

	public java.lang.String getClazzRequire() {
		return get("clazz_require");
	}

	public void setClazzHour(java.lang.Integer clazzHour) {
		set("clazz_hour", clazzHour);
	}

	public java.lang.Integer getClazzHour() {
		return get("clazz_hour");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
