package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsg<M extends BaseMsg<M>> extends Model<M> implements IBean {

	public void setMsgId(java.lang.Integer msgId) {
		set("msg_id", msgId);
	}

	public java.lang.Integer getMsgId() {
		return get("msg_id");
	}

	public void setMsgFromId(java.lang.Integer msgFromId) {
		set("msg_from_id", msgFromId);
	}

	public java.lang.Integer getMsgFromId() {
		return get("msg_from_id");
	}

	public void setMsgToId(java.lang.Integer msgToId) {
		set("msg_to_id", msgToId);
	}

	public java.lang.Integer getMsgToId() {
		return get("msg_to_id");
	}

	public void setMsgTitle(java.lang.String msgTitle) {
		set("msg_title", msgTitle);
	}

	public java.lang.String getMsgTitle() {
		return get("msg_title");
	}

	public void setMsgContent(java.lang.String msgContent) {
		set("msg_content", msgContent);
	}

	public java.lang.String getMsgContent() {
		return get("msg_content");
	}

	public void setMsgType(java.lang.Integer msgType) {
		set("msg_type", msgType);
	}

	public java.lang.Integer getMsgType() {
		return get("msg_type");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

}
