package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobTemplate<M extends BaseJobTemplate<M>> extends Model<M> implements IBean {

	public void setTmpId(java.lang.Integer tmpId) {
		set("tmp_id", tmpId);
	}

	public java.lang.Integer getTmpId() {
		return get("tmp_id");
	}

	public void setTmpJobName(java.lang.String tmpJobName) {
		set("tmp_job_name", tmpJobName);
	}

	public java.lang.String getTmpJobName() {
		return get("tmp_job_name");
	}

	public void setTmpJobNum(java.lang.Integer tmpJobNum) {
		set("tmp_job_num", tmpJobNum);
	}

	public java.lang.Integer getTmpJobNum() {
		return get("tmp_job_num");
	}

	public void setTmpDepart(java.lang.String tmpDepart) {
		set("tmp_depart", tmpDepart);
	}

	public java.lang.String getTmpDepart() {
		return get("tmp_depart");
	}

	public void setTmpDepartContact(java.lang.String tmpDepartContact) {
		set("tmp_depart_contact", tmpDepartContact);
	}

	public java.lang.String getTmpDepartContact() {
		return get("tmp_depart_contact");
	}

	public void setTmpJobAddr(java.lang.String tmpJobAddr) {
		set("tmp_job_addr", tmpJobAddr);
	}

	public java.lang.String getTmpJobAddr() {
		return get("tmp_job_addr");
	}

	public void setTmpJobCategory(java.lang.String tmpJobCategory) {
		set("tmp_job_category", tmpJobCategory);
	}

	public java.lang.String getTmpJobCategory() {
		return get("tmp_job_category");
	}

	public void setTmpJobExperYear(java.lang.String tmpJobExperYear) {
		set("tmp_job_exper_year", tmpJobExperYear);
	}

	public java.lang.String getTmpJobExperYear() {
		return get("tmp_job_exper_year");
	}

	public void setTmpJobDesc(java.lang.String tmpJobDesc) {
		set("tmp_job_desc", tmpJobDesc);
	}

	public java.lang.String getTmpJobDesc() {
		return get("tmp_job_desc");
	}

	public void setTmpJobRequire(java.lang.String tmpJobRequire) {
		set("tmp_job_require", tmpJobRequire);
	}

	public java.lang.String getTmpJobRequire() {
		return get("tmp_job_require");
	}

	public void setTmpSpecialRequire(java.lang.String tmpSpecialRequire) {
		set("tmp_special_require", tmpSpecialRequire);
	}

	public java.lang.String getTmpSpecialRequire() {
		return get("tmp_special_require");
	}

	public void setTmpSalary(java.lang.String tmpSalary) {
		set("tmp_salary", tmpSalary);
	}

	public java.lang.String getTmpSalary() {
		return get("tmp_salary");
	}

	public void setTmpUrgency(java.lang.Integer tmpUrgency) {
		set("tmp_urgency", tmpUrgency);
	}

	public java.lang.Integer getTmpUrgency() {
		return get("tmp_urgency");
	}

	public void setDeadtime(java.util.Date deadtime) {
		set("deadtime", deadtime);
	}

	public java.util.Date getDeadtime() {
		return get("deadtime");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
