package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCompanyR<M extends BaseUserCompanyR<M>> extends Model<M> implements IBean {

	public void setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
	}

	public java.lang.Integer getCompanyId() {
		return get("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public void setCompanyAddr(java.lang.String companyAddr) {
		set("company_addr", companyAddr);
	}

	public java.lang.String getCompanyAddr() {
		return get("company_addr");
	}

	public void setCompanyContact(java.lang.String companyContact) {
		set("company_contact", companyContact);
	}

	public java.lang.String getCompanyContact() {
		return get("company_contact");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

}
