package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClazz<M extends BaseClazz<M>> extends Model<M> implements IBean {

	public void setClassId(java.lang.Integer classId) {
		set("class_id", classId);
	}

	public java.lang.Integer getClassId() {
		return get("class_id");
	}

	public void setClassName(java.lang.String className) {
		set("class_name", className);
	}

	public java.lang.String getClassName() {
		return get("class_name");
	}

	public void setClassDesc(java.lang.String classDesc) {
		set("class_desc", classDesc);
	}

	public java.lang.String getClassDesc() {
		return get("class_desc");
	}

	public void setClassImg(java.lang.String classImg) {
		set("class_img", classImg);
	}

	public java.lang.String getClassImg() {
		return get("class_img");
	}

	public void setClassRequire(java.lang.String classRequire) {
		set("class_require", classRequire);
	}

	public java.lang.String getClassRequire() {
		return get("class_require");
	}

	public void setClassHour(java.lang.Integer classHour) {
		set("class_hour", classHour);
	}

	public java.lang.Integer getClassHour() {
		return get("class_hour");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
