package win.yulongsun.talents.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResume<M extends BaseResume<M>> extends Model<M> implements IBean {

	public void setResumeId(java.lang.Integer resumeId) {
		set("resume_id", resumeId);
	}

	public java.lang.Integer getResumeId() {
		return get("resume_id");
	}

	public void setResumeName(java.lang.String resumeName) {
		set("resume_name", resumeName);
	}

	public java.lang.String getResumeName() {
		return get("resume_name");
	}

	public void setResumeDesc(java.lang.String resumeDesc) {
		set("resume_desc", resumeDesc);
	}

	public java.lang.String getResumeDesc() {
		return get("resume_desc");
	}

	public void setResumeGender(java.lang.String resumeGender) {
		set("resume_gender", resumeGender);
	}

	public java.lang.String getResumeGender() {
		return get("resume_gender");
	}

	public void setResumeAcademy(java.lang.String resumeAcademy) {
		set("resume_academy", resumeAcademy);
	}

	public java.lang.String getResumeAcademy() {
		return get("resume_academy");
	}

	public void setResumeIsStudy(java.lang.String resumeIsStudy) {
		set("resume_is_study", resumeIsStudy);
	}

	public java.lang.String getResumeIsStudy() {
		return get("resume_is_study");
	}

	public void setMajor(java.lang.String major) {
		set("major", major);
	}

	public java.lang.String getMajor() {
		return get("major");
	}

	public void setGraduateAt(java.lang.String graduateAt) {
		set("graduate_at", graduateAt);
	}

	public java.lang.String getGraduateAt() {
		return get("graduate_at");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}

	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
